version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/myapp
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    container_name: php
    build:
      ./php
    volumes:
      - ./src:/var/www/myapp
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    image: mariadb
    container_name: db
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/app
    entrypoint:
      - composer
      - install
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
